### ISSUE TITLE
Support for table_schemas other than public

### ISSUE THREAD

**Issue by TimSullivan** [zed-extensions/postgres-context-server#1]
I love this extension so much. ❤️

I have some databases that include schemas for tables that aren't `public` (for example, `salesforce`), so I'm wondering if the code could be updated to support tables in those schemas. All Tables brings them in, though without the `salesforce.` before the names.

**Comment by notpeter** [comment]
I think would need to implemented on the node side of this extension, you can find that here:
- https://github.com/zed-industries/postgres-context-server/
