### ISSUE TITLE
Where is `/pg-schema` being set as the slash command?

### ISSUE THREAD

**Issue by g0t4** [zed-extensions/postgres-context-server#2]
I can't find the slash command text outside of the readme?

Is this housed in a different extension or zed itself?

**Comment by g0t4** [comment]
Ahh ok I found it inside the context server itself, which isn't yet on GitHub (FTR https://www.npmjs.com/package/@zeddotdev/postgres-context-server) 

It also might help to clarify what MCP features are supported. It appears that tools aren't supported (yet?) - https://modelcontextprotocol.io/clients

**Comment by notpeter** [comment]
Hi @g0t4,

The code for that npm package is available here:

- https://github.com/zed-industries/postgres-context-server/

It was an oversight that the repo was not published publicly with the official launch. My apologies.

> It also might help to clarify what MCP features are supported. It appears that tools aren't supported (yet?) - https://modelcontextprotocol.io/clients

There's some limited documentation here: https://zed.dev/docs/assistant/model-context-protocol but it's certainly a little thin on details.

**Comment by g0t4** [comment]
Thank you!

Wes Higbee
